name: Build LaTeX document

on: [push,pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-publishers texlive-science latexmk
      - name: Compile LaTeX document
        run: |
          cd Document/LaTeX
          make
      - name: Check pdf files
        run: |
          set -e
          file Document/LaTeX/ArticleExample.pdf | grep -q ' PDF '
